import { ChakraProvider } from '@chakra-ui/react';
import { ClerkProvider } from '@clerk/nextjs';
import { type AppType } from 'next/app';
import Head from 'next/head';
import { theme } from '~/chakra/theme';
import { ruRU } from '~/localization/ru';
import '~/styles/globals.css';
import { api } from '~/utils/api';

const MyApp: AppType = ({ Component, pageProps }) => {
	return (
		<ChakraProvider theme={theme}>
			<ClerkProvider localization={ruRU}>
				<Head>
					<title>Vozduh | Украшения из серебра</title>
					<meta
						name="description"
						content="Generated by create-t3-app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Component {...pageProps} />
			</ClerkProvider>
		</ChakraProvider>
	);
};

export default api.withTRPC(MyApp);
