import { ChakraProvider, ColorModeScript } from '@chakra-ui/react';
import { ruRU } from '@clerk/localizations';
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import { type AppType } from 'next/app';
import Head from 'next/head';
import Menu from '~/UI/Menu';
import Navigation from '~/UI/Navigation/Navigation';
import { theme } from '~/chakra/theme';
import { CartProvider } from '~/context/cartContext';
import '~/styles/globals.css';
import { api } from '~/utils/api';

const MyApp: AppType = ({ Component, pageProps }) => {
	return (
		<ChakraProvider theme={theme}>
			<ColorModeScript initialColorMode={'system'} />
			<ClerkProvider localization={ruRU}>
				<CartProvider>
					<Head>
						<title>Vozduh | Украшения из серебра</title>
						<meta
							name="description"
							content="Generated by create-t3-app"
						/>
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<Navigation />
					<SignedIn>
						<Menu />
					</SignedIn>
					<Component {...pageProps} />
				</CartProvider>
			</ClerkProvider>
		</ChakraProvider>
	);
};

export default api.withTRPC(MyApp);
